apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-node-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-node-app1
  template:
    metadata:
      labels:
        app: sample-node-app1
    spec:
      containers:
      - name: sample-node-app1
        image: sample-node-app1:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: mongodb://mongo:27017/sampledb

