apiVersion: v1
kind: Service
metadata:
  name: sample-node-app1
spec:
  type: NodePort
  selector:
    app: sample-node-app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080

